const MAX_TIMESPAN_SECONDS = 60 * 5;
const DEFAULT_MAX_BUCKET_SIZE = Math.ceil(MAX_TIMESPAN_SECONDS / 10);
const GARBAGE_COLLECTION_INTERVAL_MS = Math.floor((MAX_TIMESPAN_SECONDS * 1000) / 2);

export {
    DEFAULT_MAX_BUCKET_SIZE,
    MAX_TIMESPAN_SECONDS,
    GARBAGE_COLLECTION_INTERVAL_MS,
};
